// Copyright 2013 The Flutter Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8_0000_0000_0000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum SourceCamera: Int, CaseIterable {
  case rear = 0
  case front = 1
}

enum SourceType: Int, CaseIterable {
  case camera = 0
  case gallery = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct MaxSize: Hashable, CustomStringConvertible {
  var width: Double? = nil
  var height: Double? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MaxSize? {
    let width: Double? = nilOrValue(pigeonVar_list[0])
    let height: Double? = nilOrValue(pigeonVar_list[1])

    return MaxSize(
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
    ]
  }
  static func == (lhs: MaxSize, rhs: MaxSize) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.width, rhs.width)
      && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MaxSize")
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "MaxSize(width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaSelectionOptions: Hashable, CustomStringConvertible {
  var maxSize: MaxSize
  var imageQuality: Int64? = nil
  var requestFullMetadata: Bool
  var allowMultiple: Bool
  var limit: Int64? = nil

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaSelectionOptions? {
    let maxSize = pigeonVar_list[0] as! MaxSize
    let imageQuality: Int64? = nilOrValue(pigeonVar_list[1])
    let requestFullMetadata = pigeonVar_list[2] as! Bool
    let allowMultiple = pigeonVar_list[3] as! Bool
    let limit: Int64? = nilOrValue(pigeonVar_list[4])

    return MediaSelectionOptions(
      maxSize: maxSize,
      imageQuality: imageQuality,
      requestFullMetadata: requestFullMetadata,
      allowMultiple: allowMultiple,
      limit: limit
    )
  }
  func toList() -> [Any?] {
    return [
      maxSize,
      imageQuality,
      requestFullMetadata,
      allowMultiple,
      limit,
    ]
  }
  static func == (lhs: MediaSelectionOptions, rhs: MediaSelectionOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.maxSize, rhs.maxSize)
      && MessagesPigeonInternal.deepEquals(lhs.imageQuality, rhs.imageQuality)
      && MessagesPigeonInternal.deepEquals(lhs.requestFullMetadata, rhs.requestFullMetadata)
      && MessagesPigeonInternal.deepEquals(lhs.allowMultiple, rhs.allowMultiple)
      && MessagesPigeonInternal.deepEquals(lhs.limit, rhs.limit)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaSelectionOptions")
    MessagesPigeonInternal.deepHash(value: maxSize, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: imageQuality, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: requestFullMetadata, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: allowMultiple, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: limit, hasher: &hasher)
  }

  public var description: String {
    return
      "MediaSelectionOptions(maxSize: \(String(describing: maxSize)), imageQuality: \(String(describing: imageQuality)), requestFullMetadata: \(String(describing: requestFullMetadata)), allowMultiple: \(String(describing: allowMultiple)), limit: \(String(describing: limit)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SourceSpecification: Hashable, CustomStringConvertible {
  var type: SourceType
  var camera: SourceCamera

  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SourceSpecification? {
    let type = pigeonVar_list[0] as! SourceType
    let camera = pigeonVar_list[1] as! SourceCamera

    return SourceSpecification(
      type: type,
      camera: camera
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      camera,
    ]
  }
  static func == (lhs: SourceSpecification, rhs: SourceSpecification) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.type, rhs.type)
      && MessagesPigeonInternal.deepEquals(lhs.camera, rhs.camera)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SourceSpecification")
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: camera, hasher: &hasher)
  }

  public var description: String {
    return
      "SourceSpecification(type: \(String(describing: type)), camera: \(String(describing: camera)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SourceCamera(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return SourceType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return MaxSize.fromList(self.readValue() as! [Any?])
    case 132:
      return MediaSelectionOptions.fromList(self.readValue() as! [Any?])
    case 133:
      return SourceSpecification.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? SourceCamera {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? SourceType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? MaxSize {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? MediaSelectionOptions {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? SourceSpecification {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ImagePickerApi {
  func pickImage(
    source: SourceSpecification, maxSize: MaxSize, imageQuality: Int64?, requestFullMetadata: Bool,
    completion: @escaping (Result<String?, Error>) -> Void)
  func pickMultiImage(
    maxSize: MaxSize, imageQuality: Int64?, requestFullMetadata: Bool, limit: Int64?,
    completion: @escaping (Result<[String], Error>) -> Void)
  func pickVideo(
    source: SourceSpecification, maxDurationSeconds: Int64?,
    completion: @escaping (Result<String?, Error>) -> Void)
  func pickMultiVideo(
    maxDurationSeconds: Int64?, limit: Int64?,
    completion: @escaping (Result<[String], Error>) -> Void)
  /// Selects images and videos and returns their paths.
  func pickMedia(
    mediaSelectionOptions: MediaSelectionOptions,
    completion: @escaping (Result<[String], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ImagePickerApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ImagePickerApi` to handle messages through the `binaryMessenger`.
  static func setUp(
    binaryMessenger: FlutterBinaryMessenger, api: ImagePickerApi?, messageChannelSuffix: String = ""
  ) {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let pickImageChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.image_picker_ios.ImagePickerApi.pickImage\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sourceArg = args[0] as! SourceSpecification
        let maxSizeArg = args[1] as! MaxSize
        let imageQualityArg: Int64? = nilOrValue(args[2])
        let requestFullMetadataArg = args[3] as! Bool
        api.pickImage(
          source: sourceArg, maxSize: maxSizeArg, imageQuality: imageQualityArg,
          requestFullMetadata: requestFullMetadataArg
        ) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickImageChannel.setMessageHandler(nil)
    }
    let pickMultiImageChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.image_picker_ios.ImagePickerApi.pickMultiImage\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickMultiImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let maxSizeArg = args[0] as! MaxSize
        let imageQualityArg: Int64? = nilOrValue(args[1])
        let requestFullMetadataArg = args[2] as! Bool
        let limitArg: Int64? = nilOrValue(args[3])
        api.pickMultiImage(
          maxSize: maxSizeArg, imageQuality: imageQualityArg,
          requestFullMetadata: requestFullMetadataArg, limit: limitArg
        ) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickMultiImageChannel.setMessageHandler(nil)
    }
    let pickVideoChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.image_picker_ios.ImagePickerApi.pickVideo\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sourceArg = args[0] as! SourceSpecification
        let maxDurationSecondsArg: Int64? = nilOrValue(args[1])
        api.pickVideo(source: sourceArg, maxDurationSeconds: maxDurationSecondsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickVideoChannel.setMessageHandler(nil)
    }
    let pickMultiVideoChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.image_picker_ios.ImagePickerApi.pickMultiVideo\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickMultiVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let maxDurationSecondsArg: Int64? = nilOrValue(args[0])
        let limitArg: Int64? = nilOrValue(args[1])
        api.pickMultiVideo(maxDurationSeconds: maxDurationSecondsArg, limit: limitArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickMultiVideoChannel.setMessageHandler(nil)
    }
    /// Selects images and videos and returns their paths.
    let pickMediaChannel = FlutterBasicMessageChannel(
      name: "dev.flutter.pigeon.image_picker_ios.ImagePickerApi.pickMedia\(channelSuffix)",
      binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickMediaChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let mediaSelectionOptionsArg = args[0] as! MediaSelectionOptions
        api.pickMedia(mediaSelectionOptions: mediaSelectionOptionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickMediaChannel.setMessageHandler(nil)
    }
  }
}
